# Generated by Django 4.0.7 on 2022-09-10 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField(verbose_name='Data Consulta')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('especialidade', models.CharField(choices=[('1', 'Alergista'), ('2', 'Cardiologia'), ('3', 'Clinico Geral'), ('4', 'Dermatologia'), ('5', 'Endocrinologia'), ('6', 'Fisiatria'), ('7', 'Fonoaudiologia'), ('8', 'Gastroenterologia'), ('9', 'Geriatria'), ('10', 'Ginecologia'), ('11', 'Nefrologia'), ('12', 'Neurologia'), ('13', 'Nutrição'), ('14', 'Obstetrícia'), (
                    '15', 'Odontologia'), ('16', 'Oftalmologia'), ('17', 'Oncologia'), ('18', 'Ortopedia'), ('19', 'Otorrinolaringologia'), ('20', 'Pediatria'), ('21', 'Pneumologia'), ('22', 'Proctologia'), ('23', 'Psicologia'), ('24', 'Psiquiatria'), ('25', 'Reumatologia'), ('26', 'Traumatologia'), ('27', 'Urologia'), ('28', 'Outras')], max_length=30, verbose_name='Especialidade')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local')),
                ('nome_especialista', models.CharField(max_length=100, verbose_name='Especialista')),
                ('fone_contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fone')),
                ('atendimento', models.CharField(choices=[('1', 'Primeira'), ('2', 'Retorno-Exames'), ('3',
                 'Retorno'), ('4', 'Emergência'), ('5', 'Remoto')], max_length=30, verbose_name='Atendimento')),
                ('motivo_consulta', models.CharField(blank=True, max_length=300, null=True, verbose_name='Motivo Consulta')),
                ('sintomas', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sintomas')),
                ('observacao', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observação')),
                ('cancelamento', models.DateField(blank=True, null=True, verbose_name='Data Cancelamento')),
                ('motivo_cancelamento', models.CharField(blank=True, choices=[('1', 'Primeira'), ('2', 'Retorno-Exames'), (
                    '3', 'Retorno'), ('4', 'Emergência'), ('5', 'Remoto')], max_length=30, null=True, verbose_name='Motivo Cancelamento')),
                ('acompanhante_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='crm.responsavel', verbose_name='Acompanhante Responsável')),
                ('dependente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='consultas', to='crm.dependente')),
            ],
            options={
                'ordering': ('data_consulta', 'hora'),
            },
        ),
        migrations.CreateModel(
            name='PosConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('tratamento', models.TextField(blank=True, null=True, verbose_name='Tratamento')),
                ('receita', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Upload Receita')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('acompanhante_responsavel', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='crm.responsavel', verbose_name='Responsável')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='pos_consultas', to='consulta.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_prescrito', models.CharField(max_length=100, verbose_name='Medicamento Prescrito')),
                ('principio_ativo', models.CharField(blank=True, max_length=40, verbose_name='Princípo Ativo')),
                ('indicacoes', models.TextField(blank=True, null=True, verbose_name='Indicações')),
                ('tipo_medicamento', models.CharField(choices=[('1', 'Comprimido'), ('2', 'Cápsulas'), ('3', 'Creme'), ('4', 'Gotas'), ('5', 'Injeção Musc'), ('6', 'Injeção Subcutânea'), (
                    '7', 'Injeção Venosa'), ('8', 'Pomada'), ('9', 'Solução'), ('10', 'Spray'), ('11', 'Supositório'), ('12', 'Outros')], max_length=18, verbose_name='Tipo de Medicamento')),
                ('dosagem', models.CharField(max_length=40, verbose_name='Dosagem')),
                ('posologia', models.CharField(choices=[('1 vez ', '1 vez'), ('2 vezes ', '2 vezes'), ('3 vezes ', '3 vezes'), (
                    '4 vezes ', '4 vezes'), ('5 vezes ', '5 vezes'), ('6 vezes ', '6 vezes')], max_length=30, verbose_name='Posologia')),
                ('uso_continuo', models.CharField(choices=[('Sim ', 'Sim'),
                 ('Não ', 'Não')], max_length=30, verbose_name='Uso Continuo')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('forma_uso', models.TextField(verbose_name='Forma de Uso')),
                ('orientacao_tratamento', models.TextField(verbose_name='Orientações')),
                ('medico_responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Médico Responsável')),
                ('fornecedor_principal', models.CharField(choices=[('1', 'Farmácia Hospital'), ('2', 'Farmácia Popular'), (
                    '3', 'Farmácia - Drogaria'), ('4', 'Drogaria - Site'), ('5', 'Mercado Livre'), ('6', 'Outros')], max_length=20, verbose_name='Fornecedor')),
                ('dependente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.dependente')),
            ],
            options={
                'ordering': ('dependente', 'medicamento_prescrito'),
            },
        ),
        migrations.CreateModel(
            name='JornadaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_entrada', models.DateTimeField(verbose_name='Data/Hora entrada')),
                ('dh_saida', models.DateTimeField(verbose_name='Data/Hora saída')),
                ('horas_trabalhadas_diaria', models.DurationField(verbose_name='Horas Diarias')),
                ('soma_horas_semanal', models.DurationField(verbose_name='Horas semanais')),
                ('soma_horas_mensal', models.DurationField(verbose_name='Horas mensais')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='funcionario', to='crm.cuidador', verbose_name='funcionario')),
                ('responsavel_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='responsavel_dia', to='crm.responsavel', verbose_name='Responsavel do dia')),
            ],
            options={
                'verbose_name': ('Jornada de Trabalho',),
                'verbose_name_plural': 'Joranadas de Trabalho',
                'ordering': ('dh_entrada',),
            },
        ),
        migrations.CreateModel(
            name='Glicose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_medicao', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('estado_alimentar', models.CharField(choices=[('1', 'Em jejum'), ('2', 'Após café da manhã'), ('3', 'Antes de almoçar'), ('4', 'Após almoço'), (
                    '5', 'Antes do jantar'), ('6', 'Após jantar'), ('7', 'Antes de dormir'), ('8', 'Na madrugada')], max_length=30, verbose_name='Estado Alimentar')),
                ('taxa_glicose', models.IntegerField(verbose_name='Taxa de Glicose')),
                ('alimentos', models.TextField(blank=True, null=True, verbose_name='Alimentação')),
                ('tipo_insulina', models.CharField(blank=True, choices=[
                 ('1', 'Lantus'), ('2', 'NovoRapid'), ('3', 'Nenhuma')], max_length=30, null=True, verbose_name='Tipo da Insulina')),
                ('qt_insulina', models.IntegerField(default=0, verbose_name='Quant. aplicada')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('media_diaria', models.DecimalField(blank=True, decimal_places=2,
                 default=0, max_digits=10, null=True, verbose_name='Media Diária')),
                ('media_mensal', models.DecimalField(blank=True, decimal_places=2,
                 default=0, max_digits=10, null=True, verbose_name='Media Mensal')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='Cuidador', to='crm.cuidador', verbose_name='Cuidador')),
                ('dependente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='crm.dependente', verbose_name='Dependente')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='Responsavel', to='crm.responsavel', verbose_name='Responsável')),
            ],
            options={
                'ordering': ('data_medicao', 'hora'),
            },
        ),
        migrations.CreateModel(
            name='EscalaResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Chegada')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Chegada')),
                ('data_saida_presencial', models.DateField(null=True, verbose_name='Data Saída Presencial')),
                ('qt_dias_presenciais', models.IntegerField(default=0, verbose_name='Quant. dias presenciais ')),
                ('qt_horas_presentes', models.DecimalField(decimal_places=2,
                 default=0, max_digits=4, verbose_name='Quant. horas')),
                ('hora_saida_presencial', models.TimeField(verbose_name='Hora de Saída')),
                ('data_fim', models.DateField(null=True, verbose_name='Data Final do Plantão')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('responsavel_monitoramento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='responsavel_monitoramento', to='crm.responsavel', verbose_name='Resp. Monitoramento')),
                ('responsavel_presencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='responsavel_presencial', to='crm.responsavel', verbose_name='Resp. Presencial')),
            ],
            options={
                'verbose_name': 'Escala Responsável',
                'verbose_name_plural': 'Escalas Responsáveis',
                'ordering': ('data_inicio', 'hora_inicio'),
            },
        ),
    ]
