# Generated by Django 4.0.7 on 2022-09-10 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posconsulta',
            name='receita',
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receita', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Upload Receita')),
                ('pos_consulta', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='consulta.posconsulta')),
            ],
        ),
    ]
