# Generated by Django 4.0.5 on 2022-09-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_alter_consulta_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posconsulta',
            name='receita',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Upload Receita'),
        ),
    ]
