# Generated by Django 4.0.7 on 2022-09-10 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_remove_posconsulta_receita_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='pos_consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='receitas', to='consulta.posconsulta'),
        ),
    ]
