# Generated by Django 4.0.5 on 2022-07-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_alter_medicamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='data_fim',
            field=models.DateField(blank=True, null=True,
                                   verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='data_inicio',
            field=models.DateField(blank=True, null=True,
                                   verbose_name='Data Início'),
        ),
    ]
