# Generated by Django 4.0.6 on 2022-07-23 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_delete_dependente_dependente'),
        ('consulta', '0003_alter_medicamento_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Consulta',
            name='dependente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='consultas', to='crm.dependente'),
        ),
        migrations.AlterField(
            model_name='Medicamento',
            name='dependente',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='crm.dependente'),
        ),
    ]
