# Generated by Django 4.0.5 on 2022-09-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_alter_posconsulta_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posconsulta',
            name='receita',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Upload Receita'),
        ),
    ]
