# Generated by Django 4.0.5 on 2022-09-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_alter_receita_pos_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaresponsavel',
            name='qt_horas_presentes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Quant. horas'),
        ),
    ]
