# Generated by Django 4.0.5 on 2022-09-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_alter_escalaresponsavel_qt_horas_presentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaresponsavel',
            name='qt_dias_presenciais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6,
                                      verbose_name='Quant. dias presenciais '),
        ),
    ]
