# Generated by Django 4.0.5 on 2022-07-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_taxa_glicose'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxa_glicose',
            name='alimentos',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Alimentação'),
        ),
        migrations.AddField(
            model_name='taxa_glicose',
            name='observacao',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Observação'),
        ),
    ]
