# Generated by Django 4.0.5 on 2022-09-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_alter_escalaresponsavel_qt_dias_presenciais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaresponsavel',
            name='qt_dias_presenciais',
            field=models.IntegerField(default=0, verbose_name='Quant. dias presenciais '),
        ),
    ]
