# Generated by Django 4.0.5 on 2022-07-27 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_delete_dependente_dependente'),
        ('consulta', '0006_taxa_glicose_alimentos_taxa_glicose_observacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taxa_glicose',
            new_name='Glicose',
        ),
    ]
