# Generated by Django 4.0.5 on 2022-07-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0007_rename_taxa_glicose_glicose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glicose',
            name='media_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=0,
                                      max_digits=10, null=True, verbose_name='Media Diária'),
        ),
        migrations.AlterField(
            model_name='glicose',
            name='media_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0,
                                      max_digits=10, null=True, verbose_name='Media Mensal'),
        ),
    ]
