# Generated by Django 4.0.5 on 2022-07-27 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_delete_dependente_dependente'),
        ('consulta', '0008_alter_glicose_media_diaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glicose',
            name='qt_insulina',
            field=models.IntegerField(
                default=0, max_length=2, verbose_name='Qtdade aplicada'),
        ),
        migrations.AddField(
            model_name='glicose',
            name='tipo_insulina',
            field=models.CharField(blank=True, choices=[('1', 'Lantus'), (
                '2', 'NovoRapid')], max_length=30, null=True, verbose_name='Tipo da Insulina'),
        ),
        migrations.AlterField(
            model_name='glicose',
            name='cuidador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='Cuidador', to='crm.cuidador', verbose_name='Cuidador'),
        ),
        migrations.AlterField(
            model_name='glicose',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='Responsavel', to='crm.responsavel', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='glicose',
            name='taxa_glicose',
            field=models.IntegerField(
                max_length=3, verbose_name='Taxa de Glicose'),
        ),
    ]
