# Generated by Django 4.0.5 on 2022-09-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0008_alter_posconsulta_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='exames',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Upload Exames'),
        ),
    ]
