# Generated by Django 4.0.5 on 2022-09-20 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0009_receita_exames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='exames',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='receita',
        ),
        migrations.AddField(
            model_name='receita',
            name='exame',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Upload Exames'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='pos_consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='exames', to='consulta.posconsulta'),
        ),
    ]
