# Generated by Django 4.0.5 on 2022-08-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_delete_dependente_dependente'),
        ('consulta', '0009_glicose_qt_insulina_glicose_tipo_insulina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glicose',
            name='qt_insulina',
            field=models.IntegerField(default=0, verbose_name='Quant. aplicada'),
        ),
        migrations.AlterField(
            model_name='glicose',
            name='taxa_glicose',
            field=models.IntegerField(verbose_name='Taxa de Glicose'),
        ),
        migrations.CreateModel(
            name='EscalaResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Chegada')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Chegada')),
                ('data_saida_presencial', models.DateField(null=True, verbose_name='Data Saída Presencial')),
                ('qt_dias_presenciais', models.IntegerField(default=0, verbose_name='Quant. dias presenciais ')),
                ('hora_saida_presencial', models.TimeField(verbose_name='Hora de Saída')),
                ('data_fim', models.DateField(null=True, verbose_name='Data Final')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('responsavel_monitoramento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='responsavel_monitoramento', to='crm.responsavel', verbose_name='Resp. Monitoramento')),
                ('responsavel_presencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='responsavel_presencial', to='crm.responsavel', verbose_name='Resp. Presencial')),
            ],
            options={
                'ordering': ('data_inicio', 'hora_inicio'),
            },
        ),
    ]
