# Generated by Django 4.0.5 on 2022-08-02 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_delete_dependente_dependente'),
        ('consulta', '0009_glicose_qt_insulina_glicose_tipo_insulina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaResponsaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField(verbose_name='Data Inicial')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Combinada')),
                ('data_fim', models.DateField(verbose_name='Data Final')),
                ('qt_dias', models.IntegerField(default=0, max_length=2, verbose_name='Qtdade dias')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.responsavel', verbose_name='Responsável')),
            ],
            options={
                'ordering': ('data_inicial', 'hora_inicio'),
            },
        ),
    ]
