# Generated by Django 4.0.5 on 2022-08-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0010_alter_glicose_qt_insulina_alter_glicose_taxa_glicose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaresponsavel',
            name='data_fim',
            field=models.DateField(null=True, verbose_name='Data Final do Plantão'),
        ),
    ]
