# Generated by Django 4.0.5 on 2022-09-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0011_remove_receita_exame_receita_receita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, choices=[('1', 'A pedido do médico'), ('2', 'A pedido dos responsáveis'), ('3', 'Não é mais necessária'), ('4', 'Outros')], max_length=30, null=True, verbose_name='Motivo Cancelamento'),
        ),
    ]
