# Generated by Django 4.0.5 on 2022-08-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0011_alter_escalaresponsavel_data_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaresponsavel',
            name='qt_horas_presentes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Quant. horas'),
        ),
    ]
