# Generated by Django 4.0.5 on 2022-09-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0012_alter_consulta_motivo_cancelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='exame',
            field=models.ImageField(blank=True, null=True, upload_to='exames/', verbose_name='Upload Exames'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='receita',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/', verbose_name='Upload Receita'),
        ),
    ]
