# Generated by Django 4.0.7 on 2022-08-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0012_escalaresponsavel_qt_horas_presentes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalaresponsavel',
            options={'ordering': ('data_inicio', 'hora_inicio'), 'verbose_name': 'Escala Responsável',
                     'verbose_name_plural': 'Escalas Responsáveis'},
        ),
    ]
