# Generated by Django 4.0.5 on 2022-08-18 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_delete_dependente_dependente'),
        ('consulta', '0013_alter_escalaresponsavel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_entrada', models.DateTimeField(verbose_name='Data/Hora entrada')),
                ('dh_saida', models.DateTimeField(verbose_name='Data/Hora saída')),
                ('horas_trabalhadas_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Horas Diarias')),
                ('soma_horas_semanal', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Horas semanais')),
                ('soma_horas_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Horas mensais')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='crm.cuidador', verbose_name='funcionario')),
                ('responsavel_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_dia', to='crm.responsavel', verbose_name='Responsavel do dia')),
            ],
            options={
                'verbose_name': ('Jornada de Trabalho',),
                'verbose_name_plural': 'Joranadas de Trabalho',
                'ordering': ('dh_entrada',),
            },
        ),
    ]
