# Generated by Django 4.0.5 on 2022-10-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0013_alter_exame_exame_alter_receita_receita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-data_consulta', '-hora']},
        ),
        migrations.AlterModelOptions(
            name='medicamento',
            options={'ordering': ['medicamento_prescrito']},
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fornecedor_principal',
            field=models.CharField(choices=[('1', 'Farmácia Hospital'), ('2', 'Farmácia Popular'), ('3', 'Farmácia - Drogaria'), ('4', 'Farmácia de Manipulação'), ('5', 'Drogaria - Site'), ('6', 'Mercado Livre'), ('7', 'Outros')], max_length=20, verbose_name='Fornecedor'),
        ),
    ]
