# Generated by Django 4.0.5 on 2022-10-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0014_alter_consulta_options_alter_medicamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': None},
        ),
    ]
