# Generated by Django 4.0.5 on 2022-08-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0014_jornadatrabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadatrabalho',
            name='horas_trabalhadas_diaria',
            field=models.DateTimeField(verbose_name='Horas Diarias'),
        ),
        migrations.AlterField(
            model_name='jornadatrabalho',
            name='soma_horas_mensal',
            field=models.DateTimeField(verbose_name='Horas mensais'),
        ),
        migrations.AlterField(
            model_name='jornadatrabalho',
            name='soma_horas_semanal',
            field=models.DateTimeField(verbose_name='Horas semanais'),
        ),
    ]
