# Generated by Django 4.0.5 on 2022-10-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0020_alter_consulta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'ordering': ('dependente', 'medicamento_prescrito')},
        ),
    ]
