# Generated by Django 4.0.5 on 2022-10-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0021_alter_medicamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glicose',
            options={'ordering': ('-data_medicao', '-hora')},
        ),
    ]
