# Generated by Django 4.0.5 on 2022-10-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0023_alter_consulta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jornadatrabalho',
            options={'ordering': ('dh_entrada', 'cuidador'), 'verbose_name': ('Jornada de Trabalho',), 'verbose_name_plural': 'Jornadas de Trabalho'},
        ),
    ]
