# Generated by Django 4.0.5 on 2022-10-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0025_glicose_ultimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='glicose',
            name='feriado',
            field=models.BooleanField(default=False, verbose_name='Feriado'),
        ),
    ]
