# Generated by Django 4.0.5 on 2022-09-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='regime_contratacao',
            field=models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('FREE', 'Free Lance'), (
                'PS', 'Prestação Serviços'), ('Outros', 'Outros')], max_length=10, null=True, verbose_name='Contratação'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='parentesco_do_responsavel',
            field=models.CharField(choices=[('F', 'Filho'), ('N', 'Neto'), ('I', 'Irmão'), ('O', 'Outro')],
                                   default='F', max_length=1, verbose_name='Parentesco do Responsável'),
        ),
    ]
