# Generated by Django 4.0.5 on 2022-07-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_usuario_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nacionalidade',
            new_name='naturalidade',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='celular_recado',
            new_name='telefone',
        ),
    ]
