# Generated by Django 4.0.5 on 2022-07-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_nacionalidade_usuario_naturalidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='naturalidade',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
