# Generated by Django 4.0.6 on 2022-07-23 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_usuario_parentesco_do_responsavel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dependente',
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True,
                 max_length=200, null=True, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True,
                 max_length=200, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True,
                 max_length=200, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), (
                    'PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('first_name', models.CharField(
                    blank=True, max_length=150, verbose_name='nome')),
                ('last_name', models.CharField(blank=True,
                 max_length=150, verbose_name='sobrenome')),
                ('data_nascimento', models.DateField(blank=True,
                 null=True, verbose_name='Data de Nascimento')),
                ('rg', models.CharField(blank=True,
                 max_length=20, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True,
                 max_length=14, null=True, verbose_name='CPF')),
                ('celular_whatsapp', models.CharField(blank=True, max_length=20,
                 null=True, unique=True, verbose_name='WhatsApp')),
                ('telefone', models.CharField(blank=True,
                 max_length=20, null=True, verbose_name='Telefone')),
                ('estado_civil', models.CharField(blank=True, choices=[('1', 'Solteiro(a)'), ('2', 'Casado(a)'), ('3', 'Divorciado(a)'), (
                    '4', 'Viuvo(a)'), ('5', 'União Estável'), ('6', 'Outros')], max_length=1, null=True, verbose_name='Estado Civil')),
                ('nome_conjuge', models.CharField(blank=True,
                 max_length=100, null=True, verbose_name='Cônjuge')),
                ('naturalidade', models.CharField(blank=True,
                 max_length=100, null=True, verbose_name='Naturalidade')),
                ('parentesco_do_responsavel', models.CharField(choices=[('F', 'Filho'), ('N', 'Neto'), (
                    'I', 'Irmão'), ('O', 'Outro')], max_length=1, verbose_name='Parentesco do Responsável')),
                ('dependente_convenio_medico', models.CharField(
                    blank=True, max_length=100, null=True, verbose_name='Convênio')),
                ('dependente_contato_fone_convenio', models.CharField(
                    blank=True, max_length=20, null=True, verbose_name='Telefone Convênio')),
                ('dependente_contato_endereco_convenio', models.CharField(
                    blank=True, max_length=100, null=True, verbose_name='Endereço Convênio')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='dependentes', to='crm.familia', verbose_name='Família')),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
    ]
