# Generated by Django 4.0.5 on 2022-09-24 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_alter_dependente_parentesco_do_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasBancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='Data Abertura')),
                ('nome_banco', models.CharField(max_length=30, verbose_name='Nome do Banco')),
                ('numero_banco', models.IntegerField(verbose_name='Número banco')),
                ('agencia', models.CharField(default=0, max_length=10, verbose_name='Agência')),
                ('cidade', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cidade')),
                ('conta', models.CharField(choices=[('1', 'Corrente'), ('2', 'Poupança')], max_length=30, verbose_name='Tipo conta')),
                ('numero_conta', models.CharField(max_length=30, verbose_name='Número conta')),
                ('conjunta', models.CharField(choices=[('1', 'sim'), ('2', 'Não')], max_length=30, verbose_name='Conjunta')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Atual')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data Encerramento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('titular_dependente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titular_dependente', to='crm.dependente', verbose_name='Nome Titular')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ('nome_banco',),
            },
        ),
    ]
