# Generated by Django 4.0.5 on 2022-09-25 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_dependente_parentesco_do_responsavel_and_more'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(verbose_name='Data Entrada')),
                ('referencia', models.CharField(choices=[('1', 'Salário'), ('2', 'Salário com 13º'), ('3', 'Reembolso'), ('4', 'Transferência entre contas'), ('5', 'Credito juros'), ('6', 'Outros')], max_length=30, verbose_name='Referência')),
                ('depositante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Depositante')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor')),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Upload Extrato')),
                ('observacao', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observação')),
                ('conta_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.contasbancarias', verbose_name='Conta Crédito')),
                ('responsavel_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.responsavel', verbose_name='Responsável')),
            ],
            options={
                'ordering': ['-data_entrada'],
            },
        ),
    ]
