# Generated by Django 4.0.5 on 2022-09-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_credito_options_remove_credito_comprovante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovante',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Upload Comprovante'),
        ),
    ]
