# Generated by Django 4.0.5 on 2022-09-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_comprovante_comprovante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovante',
            name='credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprovantes', to='financeiro.credito'),
        ),
    ]
