# Generated by Django 4.0.5 on 2022-09-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_comprovante_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovante',
            name='comprovante',
            field=models.ImageField(blank=True, default=None, null=True,
                                    upload_to='', verbose_name='Upload Comprovante'),
        ),
    ]
