# Generated by Django 4.0.5 on 2022-09-25 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_alter_comprovante_comprovante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovante',
            name='credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='comprovantes', to='financeiro.credito'),
        ),
    ]
