# Generated by Django 4.0.5 on 2022-10-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_dependente_parentesco_do_responsavel_and_more'),
        ('financeiro', '0009_alter_comprovante_comprovante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContasBancarias',
            new_name='ContaBancaria',
        ),
    ]
