# Generated by Django 4.0.5 on 2022-10-17 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_dependente_parentesco_do_responsavel_and_more'),
        ('financeiro', '0010_rename_contasbancarias_contabancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(verbose_name='Data Saída')),
                ('referencia', models.CharField(choices=[('1', 'Açougue'), ('2', 'Advogado'), ('3', 'Agropecuária -Ração e Medicamentos'), ('4', 'Água Mineral'), ('5', 'Caixa Cuidadores'), ('6', 'Combustível'), ('7', 'Conserto eletrodomésticos'), ('8', 'Consulta Medica'), ('9', 'Conta - Água'), ('10', 'Conta - Celular'), ('11', 'Conta - CPFL'), ('12', 'Conta - Funerária'), ('13', 'Conta - Carnê INSS'), ('14', 'Conta - Internet'), ('15', 'Conta - IPTU'), ('16', 'Conta - IPVA'), ('17', 'Conta - Luz'), ('18', 'Conta - Seguro'), ('19', 'Conta - Telefone Fixo'), ('20', 'Eletrodoméstico'), ('21', 'Exame'), ('22', 'Farmácia'), ('23', 'Gás de Cozinha'), ('24', 'Guia E-Social'), ('25', 'Impressões ou Cópias'), ('26', 'IOF de conta devedora'), ('27', 'Jardinagem'), ('28', 'Juros de conta devedora'), ('29', 'Leite'), ('30', 'Mão de Obra'), ('31', 'Material Conserto'), ('32', 'Material Construção'), ('33', 'Material Segurança'), ('34', 'Móveis'), ('35', 'Outros'), ('36', 'Padaria'), ('37', 'Pedágio'), ('38', 'Reembolso'), ('39', 'Roupas'), ('40', 'Salários Funcionários'), ('41', 'Supermercado'), ('42', 'Utensílios domésticos')], max_length=30, verbose_name='Referência')),
                ('forma_pagamentocredor', models.CharField(choices=[('1', 'Cheque'), ('2', 'Débito cartão'), ('3', 'Débitado em conta corrente'), ('4', 'Dinheiro')], max_length=40, verbose_name='Forma de Pagamento')),
                ('credor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pago a ')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor')),
                ('observacao', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observação')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.contabancaria', verbose_name='Conta Bancária')),
                ('responsavel_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.responsavel', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_saida'],
            },
        ),
        migrations.CreateModel(
            name='ComprovanteDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to='despesa/', verbose_name='Upload Comprovante')),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprovantes', to='financeiro.despesa')),
            ],
        ),
    ]
