# Generated by Django 4.0.5 on 2022-10-18 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_despesa_comprovantedespesa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credito',
            options={'ordering': ['-data_entrada', 'conta_credito'], 'verbose_name': 'Crédito Bancário', 'verbose_name_plural': 'Creditos Bancários'},
        ),
    ]
