# Generated by Django 4.0.5 on 2022-10-18 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_alter_credito_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credito',
            options={'ordering': ['-data_entrada'], 'verbose_name': 'Crédito Bancário', 'verbose_name_plural': 'Creditos Bancários'},
        ),
    ]
