# Generated by Django 4.0.5 on 2022-10-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_alter_credito_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='saldo_atual',
        ),
        migrations.AddField(
            model_name='credito',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Atual'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Atual'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='referencia',
            field=models.CharField(choices=[('1', 'Açougue'), ('2', 'Advogado'), ('3', 'Agropecuária -Ração e Medicamentos'), ('4', 'Água Mineral'), ('5', 'Caixa Cuidadores'), ('6', 'Combustível'), ('7', 'Conserto eletrodomésticos'), ('8', 'Consulta Medica'), ('9', 'Conta - Água'), ('10', 'Conta - Celular'), ('11', 'Conta - CPFL'), ('12', 'Conta - Funerária'), ('13', 'Conta - Carnê INSS'), ('14', 'Conta - Internet'), ('15', 'Conta - IPTU'), ('16', 'Conta - IPVA'), ('17', 'Conta - Luz'), ('18', 'Conta - Seguro'), ('19', 'Conta - Telefone Fixo'), ('20', 'Eletrodoméstico'), ('21', 'Exame'), ('22', 'Farmácia'), ('23', 'Gás de Cozinha'), ('24', 'Guia E-Social'), ('25', 'Impressões ou Cópias'), ('26', 'IOF de conta devedora'), ('27', 'Jardinagem'), ('28', 'Juros de conta devedora'), ('29', 'Leite'), ('30', 'Mão de Obra'), ('31', 'Material Conserto'), ('32', 'Material Construção'), ('33', 'Material Segurança'), ('34', 'Móveis'), ('35', 'Outros'), ('36', 'Padaria'), ('37', 'Pedágio'), ('38', 'Reembolso'), ('39', 'Roupas'), ('40', 'Salários Funcionários'), ('41', 'Saque'), ('42', 'Supermercado'), ('43', 'Utensílios domésticos')], max_length=30, verbose_name='Referência'),
        ),
    ]
