# Generated by Django 4.0.5 on 2022-10-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_remove_contabancaria_saldo_atual_credito_saldo_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Atual'),
        ),
    ]
