# Generated by Django 4.0.5 on 2022-10-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_alter_credito_options_alter_despesa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='credor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pago a '),
        ),
    ]
