# Generated by Django 4.0.5 on 2022-10-25 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_dependente_parentesco_do_responsavel_and_more'),
        ('financeiro', '0018_alter_despesa_credor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.responsavel', verbose_name='Responsável'),
        ),
    ]
