# Generated by Django 4.0.5 on 2022-10-25 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0019_contabancaria_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='responsavel',
        ),
    ]
